# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20170519_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
