# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_uploadedfile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='uploaded_file',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
