# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import reefsource.apps.albums.models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20170522_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('new', 'New upload'), ('stage_1_started', 'Stage 1 started'), ('stage_1_complete', 'Stage 1 complete'), ('stage_2_started', 'Stage 2 started'), ('stage_2_complete', 'Stage 2 complete')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.FileField(max_length=255, null=True, upload_to=reefsource.apps.albums.models.uploaded_file_to),
        ),
    ]
