# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20170523_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
