# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 04:56
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_uploadedfile_thumbnail_labeled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))]),
        ),
        migrations.AlterField(
            model_name='album',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))]),
        ),
    ]
