# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_auto_20170605_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='long',
            new_name='lng',
        ),
    ]
