# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 06:52
from __future__ import unicode_literals

import datetime
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def forward(apps, schema_editor):
    Album = apps.get_model('albums', 'Album')
    for album in Album.objects.all():
        album.lat = 0
        album.lng = 0
        album.date = album.created
        album.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0012_auto_20170605_0559'),
    ]

    operations = [
        migrations.RunPython(
            forward, backward
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='album',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))]),
        ),
        migrations.AlterField(
            model_name='album',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))]),
        ),
    ]
