# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_auto_20170605_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('new', 'New upload'), ('stage_1_started', 'Stage 1 started'), ('stage_1_complete', 'Stage 1 complete'), ('stage_1_failed', 'Stage 1 failed'), ('stage_2_started', 'Stage 2 started'), ('stage_2_complete', 'Stage 2 complete'), ('stage_2_failed', 'Stage 2 failed')], default='new', max_length=20),
        ),
    ]
