# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_auto_20170610_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'permissions': (('reanalyze_result', 'Can submit UploadedFile for analysis'),)},
        ),
    ]
